import type { ThemeId } from "@/lib/types";

export const marketingImages = {
  ocean: "/images/marketing/ocean-hero.webp",
  mountain: "/images/marketing/mountain-trek.webp",
  safari: "/images/marketing/safari-dawn.webp",
  yacht: "/images/marketing/coastal-yacht.webp",
  diving: "/images/marketing/reef-diving.webp",
  guide: "/images/marketing/local-guide.webp",
  transfer: "/images/marketing/airport-transfer.webp",
  atv: "/images/marketing/desert-atv.webp",
  planning: "/images/marketing/travel-planning.webp",
  bhutanJeep: "/images/marketing/bhutan-jeep-tour.webp",
  bhutanTrekking: "/images/marketing/bhutan-trekking-vehicle.webp",
  mountainWellness: "/images/marketing/mountain-wellness-retreat.webp",
  mountainYoga: "/images/marketing/mountain-yoga-retreat.webp",
  city: "/images/marketing/historic-city-tour.webp",
  jungle: "/images/marketing/jungle-waterfall-hike.webp",
  rail: "/images/marketing/alpine-rail-journey.webp",
  balloon: "/images/marketing/hot-air-balloon-tour.webp",
  wellness: "/images/marketing/wellness-yoga-retreat.webp",
  beach: "/images/marketing/beach-resort-stay.webp",
  desert: "/images/marketing/desert-camel-camp.webp",
  arctic: "/images/marketing/arctic-glass-igloo.webp",
  market: "/images/marketing/italian-market-tour.webp",
  jungleSafari: "/images/marketing/jungle-safari.webp",
  luxuryYacht: "/images/marketing/luxury-yacht-cove.webp",
  himalayanJeep: "/images/marketing/himalayan-jeep-tour.webp",
} as const;

export const themeMarketingImages: Record<ThemeId, string> = {
  horizon: marketingImages.city,
  "luxe-voyage": marketingImages.luxuryYacht,
  "wild-current": marketingImages.jungle,
  atlas: marketingImages.rail,
  summit: marketingImages.mountain,
  marina: marketingImages.yacht,
  dune: marketingImages.atv,
  nomad: marketingImages.planning,
  urban: marketingImages.transfer,
  escape: marketingImages.wellness,
};
